name = "Rackauckaspackage"
uuid = "69d23b7a-900e-4e39-aee0-5ee1d59a96ad"
authors = ["Alexandros Tantos"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
